### ISSUE TITLE
Bug in left right naming

### ISSUE THREAD

**Issue by loliverhennigh** [pmocz/finitevolume2-python#1]
Great code as reference! I have looking at it many times and unless I am mistaken there is a naming convention error here that tripped me up a few times, https://github.com/pmocz/finitevolume2-python/blob/main/finitevolume2.py#L118. In this case `f_XL` is actually on the right (positive direction) of the cell instead of the left (negative direction). This doesn't impact the code although it makes a little more sense using the correct naming. I think this same issue is in all your FV examples (MHD) as well.

**Comment by pmocz** [comment]
Thank you, Oliver! I'm glad you've found the code helpful.

There isn't a bug here but the naming convention is confusing, I admit.

You are right, the `f_XL` are fluxes that have been interpolated from cell centers to the `Left`. But then we have to roll other the array by one, which we do not have to do for the `f_XR` to match things up when we are constructing fluxes at interfaces.

Best,
Philip
