### ISSUE TITLE
Plotting this in 3 dimensions

### ISSUE THREAD

**Issue by nuclearglick** [pmocz/finitevolume2-python#2]
Can you please help me find a way to rotate the plot about the z-axis so that I may show it in 3-dimensions to take advantage of known symmetries in a system I wish to show a plot of?

**Comment by pmocz** [comment]
Sure! You can use `scipy`'s `interpn` function to interpolate from a 2D grid onto a 3D grid, e.g.

```python
import numpy as np
from scipy.interpolate import interpn
import matplotlib.pyplot as plt

# Create Mock 2D data in the r-z plane
N = 128
rlin = np.linspace(0, 1, N)
zlin = np.linspace(-1, 1, N)
r, z = np.meshgrid(rlin, zlin, indexing='ij')

axisym_data = np.exp(-r) * np.sin(2.0*np.pi*r)**2 * np.cos(2.0*np.pi*z)

# plot the 2D data
plt.imshow(axisym_data, origin='lower', extent=(0, 2, -1, 1))
plt.colorbar()
plt.xlabel('r')
plt.ylabel('z')
plt.savefig('data2d.png')
plt.show()

# interpolate the data to a 3d grid
xlin3d = np.linspace(-1, 1, N)
ylin3d = np.linspace(-1, 1, N)
zlin3d = np.linspace(-1, 1, N)
x3d, y3d, z3d = np.meshgrid(xlin3d, ylin3d, zlin3d, indexing='ij')

def axisym(x3d, y3d, z3d):
    r3d = np.sqrt(x3d**2 + y3d**2)
    return interpn((rlin, zlin), axisym_data, (r3d, z3d), bounds_error=False, fill_value=0)

axisym_data3d = axisym(x3d, y3d, z3d)

# Combine the two slices into one plot
fig, axs = plt.subplots(1, 2, figsize=(12, 6))

# Plot the first slice
axs[0].imshow(axisym_data3d[:, :, N//2], origin='lower', extent=(-2, 2, -2, 2))
axs[0].set_title('Slice at z = 0')
axs[0].set_xlabel('x')
axs[0].set_ylabel('y')

# Plot the second slice
axs[1].imshow(axisym_data3d[:, N//2, :], origin='lower', extent=(-2, 2, -1, 1))
axs[1].set_title('Slice at y = 0')
axs[1].set_xlabel('x')
axs[1].set_ylabel('z')

plt.tight_layout()
fig.savefig('slices3d.png')
plt.show()
```

**original 2D data**
![data2d](https://github.com/user-attachments/assets/6e126b0f-fb0d-410c-b4b7-23eca1651dd5)

**slices of the interpolated 3D data**
![slices3d](https://github.com/user-attachments/assets/5e9bd954-cd62-443d-8d33-206e22aa4195)

**Comment by pmocz** [comment]
Once you have the 3D datacube, you can use your favorite 3D plotting library or software (e.g. [yt](https://yt-project.org/), intersecting planes with [matplotlib](https://matplotlib.org/stable/gallery/mplot3d/intersecting_planes.html#sphx-glr-gallery-mplot3d-intersecting-planes-py))

**Comment by pmocz** [comment]
You can also load in 2D data to visualization software like [visit](https://visit-sphinx-github-user-manual.readthedocs.io/en/v3.0.1/gui_manual/Operators/OperatorTypes/Revolve_operator.html?highlight=example) and use the revolve operator
